name: calculator
on:
  push:
    branches:
      - '*'

jobs:
  calculator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r code/python/requirements.txt

      - name: Run tests
        run: python -m unittest discover -s code/python -p "test_*.py"

      - name: Run linters
        run: |
          flake8 code/python

      - name: Run security checks
        run: |
          bandit -r code/python