name: calculator
on:
  push:
    branches:
      - '*'

jobs:
  calculator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run linters
        run: |
          flake8 code/python