name: First Action - single 
on:
  workflow_dispatch:

jobs:
  say_hello:
    runs-on: ubuntu-latest


    steps:
      - name: First Step
        run: echo "Hello, world!"
  Bye_World:
    runs-on: ubuntu-latest
    needs: say_hello

    steps:
      - name: First Step
        run: echo "Hello, world!"
      - name: Second Step
        run: echo "Bye, world!"