name: marketplace
on:
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:
  push:
    branches:
      - '*'

jobs:
  test: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        